## Add your printers below

# name: 
#   title: "name"
#   description: "description"
#   repository: "https://raw.githubusercontent.com/your_discord_username/repo_name/refs/heads/main/Journal.md"
#   file_name: "name.md"

Hte_Hotend_Squared: 
  title: "Hte_Hotend_Squared"
  description: "toolhead attacthment for add laser cutting"
  repository: "https://raw.githubusercontent.com/Rikhav21/Printer-Mod/refs/heads/main/Journal.md"
  file_name: "Hte_Hotend_Squared.md"


Hephaestus-1V2: 
  title: "Hephaestus-1V2"
  description: "Compleate redesign of Hephaestus-1.1"
  repository: "https://raw.githubusercontent.com/BoaN235/hephaestus-3D-printer/refs/heads/main/hephaestus-1.2_journal.md"
  file_name: "Hephaestus-1.2.md"